server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:12345678@tcp(127.0.0.1:3306)/kratos?charset=utf8mb4&parseTime=True
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
snowflake:
  start_time: "2012-12-21"
  machine_id: 1
register:
  address: 127.0.0.1:8500
  scheme: http
