// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTodo = "todos"

// Todo mapped from table <todos>
type Todo struct {
	ID     int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title  *string `gorm:"column:title" json:"title"`
	Status *bool   `gorm:"column:status" json:"status"`
}

// TableName Todo's table name
func (*Todo) TableName() string {
	return TableNameTodo
}
